# For development only. Do NOT use in a production environment.
version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "homeassistant/home-assistant:latest"
    volumes:
      - ./configuration.yaml:/config/configuration.yaml:ro
      - ./custom_components:/config/custom_components:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    ports:
      - 8080:8123
